version: '3.3'
services:
    douyin_shipin:
        image: dockerqiqi/douyin:v1
        restart: always
        build:
            context: .
            dockerfile: Dockerfile            
            
        
        