SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE TABLE IF NOT EXISTS `date_model`.`Hospital_Information` (
  `TXHID` INT(64) NOT NULL AUTO_INCREMENT,
  `Region` VARCHAR(10) NOT NULL,
  `Province` VARCHAR(10) NOT NULL DEFAULT '-',
  `City` VARCHAR(10) NOT NULL DEFAULT '-',
  `Hospital_Name` VARCHAR(500) NOT NULL,
  `Trusted` BOOLEAN NOT NULL,
  PRIMARY KEY (`TXHID`),
  UNIQUE INDEX `Hospital_Name_UNIQUE` (`Hospital_Name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;
