FROM openjdk:8-jre-alpine
LABEL fruiqi <fruiqi@infervision.com>
ENV TZ=Asia/Shanghai
RUN apk add --update --no-cache tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
WORKDIR /app
COPY build/libs/label-manage-1.0.0.jar /app/
CMD ["java", "-jar", "-Dspring.profiles.active=prod", "/app/label-manage-1.0.0.jar "]


